# Generated by Django 2.2.4 on 2019-09-17 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('SB', 'Shirts And Blouses'), ('TS', 'T-Shirts'), ('SK', 'Skirts')], default='SB', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('P', 'primary'), ('W', 'warning'), ('D', 'danger')], default='P', max_length=1),
            preserve_default=False,
        ),
    ]
