# Generated by Django 2.2.4 on 2019-09-17 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190916_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('S', 'sale'), ('N', 'new'), ('P', 'promotion')], max_length=1),
        ),
    ]
