# Generated by Django 2.2.4 on 2019-09-17 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi, fugiat? Eum, blanditiis, molestias consequuntur quam ipsam nisi error voluptatum velit sequi, a rerum asperiores nemo dolores distinctio voluptatibus debitis cupiditate.'),
            preserve_default=False,
        ),
    ]
