# Generated by Django 2.2.4 on 2019-10-01 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20190930_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='exit', upload_to=''),
            preserve_default=False,
        ),
    ]
