# Generated by Django 2.2.4 on 2019-10-03 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
