# Generated by Django 2.2.4 on 2019-10-03 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('SB', 'Shirts And Blouses'), ('TS', 'T-Shirts'), ('SK', 'Skirts'), ('HS', 'Hoodies&Sweatshirts')], max_length=2),
        ),
    ]
